name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@latest
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} 
          project_id: ${{ secrets.ROJECT_ID }}  
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/test-my-app:${{ github.run_id }} .
        
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/test-my-app:latest .
          
      - name: Configure docker
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/test-my-app:${{ github.run_id }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/test-my-app:latest
    

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy okha \
            --image ${{ secrets.ARTIFACT_REGISTRY }}/test-my-app:${{ github.run_id }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --project ${{ secrets.ROJECT_ID }} \
            --min-instances=1 \ 
            --max-instances=1 \ 
            --no-cpu-boost \
            --port=80
            