name: Deploy test app Cloud Run
on:
  push:
    branches:
      - test

jobs:
  build-and-deploy-to-test-env:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: read creads..
        run: echo ${{ secrets.ARTIFACT_REGISTRY }} >> ~/text.txt
      - name: read creads2 
        run: cat ~/text.txt
