name: Deploy test app Cloud Run

on:
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy-to-test-env:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        run: echo "hello"